version : "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=elasticsearch"
      - "XPACK_SECURITY_ENABLED=false"
    networks:
      - elk
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: "30s"
      timeout: "30s"
      retries: 3
    ulimits:
      memlock:
          soft: -1
          hard: -1
      nofile:
          soft: 65536
          hard: 65536
    expose:
      - "9200"
  app:
    build: ./
    restart: always
    ports:
      - "8777:8777"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

networks:
  elk:
    driver: bridge
